// const businessDataList = [
//     // Consultancy Services - Business
//     {
//         _id: 1,
//         name: 'BizAdvise Co.',
//         category: 'Consultancy Services',
//         subcategory: 'Business',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'info@bizadvise.com',
//         phone: '+1 650-123-4567',
//         address: '123 Business St, San Francisco, CA',
//         photoUrls: [
//             'https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
//         ],
//         hours: {
//             Monday: '9:00 AM - 5:00 PM',
//             Tuesday: '9:00 AM - 5:00 PM',
//             Wednesday: '9:00 AM - 5:00 PM',
//             Thursday: '9:00 AM - 5:00 PM',
//             Friday: '9:00 AM - 5:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Providing top-notch business consulting services to help companies grow and thrive.',
//         services: [
//             { name: 'Business Strategy', description: 'Develop strategic business plans.', price: '$500' },
//             { name: 'Market Research', description: 'Conduct market analysis and research.', price: '$300' },
//         ],
//     },
//     {
//         _id: 2,
//         name: 'Growth Partners',
//         category: 'Consultancy Services',
//         subcategory: 'Business',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'contact@growthpartners.com',
//         phone: '+1 650-234-5678',
//         address: '456 Market St, San Francisco, CA',
//         hours: {
//             Monday: '9:00 AM - 6:00 PM',
//             Tuesday: '9:00 AM - 6:00 PM',
//             Wednesday: '9:00 AM - 6:00 PM',
//             Thursday: '9:00 AM - 6:00 PM',
//             Friday: '9:00 AM - 6:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Expert consultancy in business growth and management strategies.',
//         services: [
//             { name: 'Business Consulting', description: 'Personalized business advice and support.', price: '$700' },
//             { name: 'Financial Planning', description: 'Financial strategy and planning services.', price: '$400' },
//         ],
//     },
//     {
//         _id: 3,
//         name: 'Strategy Masters',
//         category: 'Consultancy Services',
//         subcategory: 'Business',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'info@strategymasters.com',
//         phone: '+1 650-345-6789',
//         address: '789 Strategy Blvd, San Francisco, CA',
//         hours: {
//             Monday: '9:00 AM - 5:00 PM',
//             Tuesday: '9:00 AM - 5:00 PM',
//             Wednesday: '9:00 AM - 5:00 PM',
//             Thursday: '9:00 AM - 5:00 PM',
//             Friday: '9:00 AM - 5:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Helping businesses define and achieve their strategic goals.',
//         services: [
//             { name: 'Strategic Planning', description: 'Long-term planning to achieve business goals.', price: '$600' },
//             { name: 'Operational Efficiency', description: 'Improve business operations and efficiency.', price: '$350' },
//         ],
//     },
//     {
//         _id: 4,
//         name: 'Peak Performance Consulting',
//         category: 'Consultancy Services',
//         subcategory: 'Business',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'contact@peakperformance.com',
//         phone: '+1 650-456-7890',
//         address: '101 Peak St, San Francisco, CA',
//         hours: {
//             Monday: '9:00 AM - 6:00 PM',
//             Tuesday: '9:00 AM - 6:00 PM',
//             Wednesday: '9:00 AM - 6:00 PM',
//             Thursday: '9:00 AM - 6:00 PM',
//             Friday: '9:00 AM - 6:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Consulting services to elevate your business performance and growth.',
//         services: [
//             { name: 'Performance Enhancement', description: 'Strategies to improve business performance.', price: '$700' },
//             { name: 'Growth Analysis', description: 'Analyze and develop growth strategies.', price: '$400' },
//         ],
//     },
//     {   
//         _id: 5,
//         name: 'Innovate Business Solutions',
//         category: 'Consultancy Services',
//         subcategory: 'Business',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'info@innovatebiz.com',
//         phone: '+1 650-567-8901',
//         address: '202 Innovation St, San Francisco, CA',
//         hours: {
//             Monday: '9:00 AM - 5:00 PM',
//             Tuesday: '9:00 AM - 5:00 PM',
//             Wednesday: '9:00 AM - 5:00 PM',
//             Thursday: '9:00 AM - 5:00 PM',
//             Friday: '9:00 AM - 5:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Driving innovation and improvement in business practices.',
//         services: [
//             { name: 'Innovation Consulting', description: 'Consulting for innovative business practices.', price: '$650' },
//             { name: 'Business Improvement', description: 'Strategies to enhance business operations.', price: '$500' },
//         ],
//     },
    
//     // Consultancy Services - IT
//     {
//         _id: 6,
//         name: 'TechSolutions',
//         category: 'Consultancy Services',
//         subcategory: 'IT',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'support@techsolutions.com',
//         phone: '+1 650-345-6789',
//         address: '789 Tech Ave, San Francisco, CA',
//         hours: {
//             Monday: '9:00 AM - 5:00 PM',
//             Tuesday: '9:00 AM - 5:00 PM',
//             Wednesday: '9:00 AM - 5:00 PM',
//             Thursday: '9:00 AM - 5:00 PM',
//             Friday: '9:00 AM - 5:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Innovative IT solutions to streamline your business operations.',
//         services: [
//             { name: 'IT Consulting', description: 'Consulting services for IT infrastructure.', price: '$600' },
//             { name: 'Cybersecurity', description: 'Protect your business from cyber threats.', price: '$800' },
//         ],
//     },
//     {
//         _id: 7,
//         name: 'CodeMasters',
//         category: 'Consultancy Services',
//         subcategory: 'IT',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'hello@codemasters.com',
//         phone: '+1 650-456-7890',
//         address: '101 Code Rd, San Francisco, CA',
//         hours: {
//             Monday: '9:00 AM - 6:00 PM',
//             Tuesday: '9:00 AM - 6:00 PM',
//             Wednesday: '9:00 AM - 6:00 PM',
//             Thursday: '9:00 AM - 6:00 PM',
//             Friday: '9:00 AM - 6:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Expert software development and IT consulting services.',
//         services: [
//             { name: 'Software Development', description: 'Custom software solutions.', price: '$1000' },
//             { name: 'IT Support', description: '24/7 IT support services.', price: '$500' },
//         ],
//     },
//     {
//         _id: 8,
//         name: 'DataWizards',
//         category: 'Consultancy Services',
//         subcategory: 'IT',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'contact@datawizards.com',
//         phone: '+1 650-567-8902',
//         address: '202 Data St, San Francisco, CA',
//         hours: {
//             Monday: '9:00 AM - 5:00 PM',
//             Tuesday: '9:00 AM - 5:00 PM',
//             Wednesday: '9:00 AM - 5:00 PM',
//             Thursday: '9:00 AM - 5:00 PM',
//             Friday: '9:00 AM - 5:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Data analysis and management consulting for improved decision-making.',
//         services: [
//             { name: 'Data Analysis', description: 'In-depth data analysis and insights.', price: '$700' },
//             { name: 'Database Management', description: 'Manage and optimize databases.', price: '$600' },
//         ],
//     },
//     {
//         _id: 9,
//         name: 'CloudConsultants',
//         category: 'Consultancy Services',
//         subcategory: 'IT',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'info@cloudconsultants.com',
//         phone: '+1 650-678-9013',
//         address: '303 Cloud St, San Francisco, CA',
//         hours: {
//             Monday: '9:00 AM - 5:00 PM',
//             Tuesday: '9:00 AM - 5:00 PM',
//             Wednesday: '9:00 AM - 5:00 PM',
//             Thursday: '9:00 AM - 5:00 PM',
//             Friday: '9:00 AM - 5:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Cloud computing solutions to enhance business operations.',
//         services: [
//             { name: 'Cloud Migration', description: 'Migrate your business operations to the cloud.', price: '$900' },
//             { name: 'Cloud Security', description: 'Ensure your cloud services are secure.', price: '$800' },
//         ],
//     },
//     {
//         _id: 10,
//         name: 'Tech Innovators',
//         category: 'Consultancy Services',
//         subcategory: 'IT',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'contact@techinnovators.com',
//         phone: '+1 650-789-0124',
//         address: '404 Innovate St, San Francisco, CA',
//         hours: {
//             Monday: '9:00 AM - 6:00 PM',
//             Tuesday: '9:00 AM - 6:00 PM',
//             Wednesday: '9:00 AM - 6:00 PM',
//             Thursday: '9:00 AM - 6:00 PM',
//             Friday: '9:00 AM - 6:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Pioneering IT solutions for modern businesses.',
//         services: [
//             { name: 'IT Strategy', description: 'Develop strategic IT plans for your business.', price: '$800' },
//             { name: 'Tech Integration', description: 'Integrate new technology into your operations.', price: '$700' },
//         ],
//     },
    
//     // Distribution - Wholesale Distribution
//     {
//         _id: 11,
//         name: 'Global Distributors',
//         category: 'Distribution',
//         subcategory: 'Wholesale Distribution',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'info@globaldist.com',
//         phone: '+1 650-567-8901',
//         address: '202 Distribution Blvd, San Francisco, CA',
//         hours: {
//             Monday: '8:00 AM - 6:00 PM',
//             Tuesday: '8:00 AM - 6:00 PM',
//             Wednesday: '8:00 AM - 6:00 PM',
//             Thursday: '8:00 AM - 6:00 PM',
//             Friday: '8:00 AM - 6:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Leading wholesale distributor for various product categories.',
//         services: [
//             { name: 'Bulk Distribution', description: 'Wholesale distribution for bulk orders.', price: '$2000' },
//             { name: 'Logistics Management', description: 'Efficient logistics and delivery solutions.', price: '$1500' },
//         ],
//     },
//     {
//         _id: 12,
//         name: 'RetailWare',
//         category: 'Distribution',
//         subcategory: 'Wholesale Distribution',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'contact@retailware.com',
//         phone: '+1 650-678-9012',
//         address: '303 Wholesale St, San Francisco, CA',
//         hours: {
//             Monday: '8:00 AM - 6:00 PM',
//             Tuesday: '8:00 AM - 6:00 PM',
//             Wednesday: '8:00 AM - 6:00 PM',
//             Thursday: '8:00 AM - 6:00 PM',
//             Friday: '8:00 AM - 6:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Specializing in wholesale distribution and supply chain solutions.',
//         services: [
//             { name: 'Product Distribution', description: 'Efficient product distribution services.', price: '$1800' },
//             { name: 'Inventory Management', description: 'Comprehensive inventory management.', price: '$1200' },
//         ],
//     },
//     {
//         _id: 13,
//         name: 'SupplyNet',
//         category: 'Distribution',
//         subcategory: 'Wholesale Distribution',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'info@supplynet.com',
//         phone: '+1 650-789-0123',
//         address: '404 Supply St, San Francisco, CA',
//         hours: {
//             Monday: '8:00 AM - 6:00 PM',
//             Tuesday: '8:00 AM - 6:00 PM',
//             Wednesday: '8:00 AM - 6:00 PM',
//             Thursday: '8:00 AM - 6:00 PM',
//             Friday: '8:00 AM - 6:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Efficient wholesale distribution for various sectors.',
//         services: [
//             { name: 'Supply Chain Solutions', description: 'End-to-end supply chain management.', price: '$2000' },
//             { name: 'Distribution Services', description: 'Reliable distribution services.', price: '$1400' },
//         ],
//     },
//     {
//         _id: 14,
//         name: 'MegaDistributors',
//         category: 'Distribution',
//         subcategory: 'Wholesale Distribution',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'contact@megadistributors.com',
//         phone: '+1 650-890-1234',
//         address: '505 Mega St, San Francisco, CA',
//         hours: {
//             Monday: '8:00 AM - 6:00 PM',
//             Tuesday: '8:00 AM - 6:00 PM',
//             Wednesday: '8:00 AM - 6:00 PM',
//             Thursday: '8:00 AM - 6:00 PM',
//             Friday: '8:00 AM - 6:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Your go-to for large-scale wholesale distribution.',
//         services: [
//             { name: 'Bulk Orders', description: 'Handling large volume wholesale orders.', price: '$2200' },
//             { name: 'Custom Solutions', description: 'Tailored distribution solutions.', price: '$1600' },
//         ],
//     },
//     {
//         _id: 15,
//         name: 'ProDistributors',
//         category: 'Distribution',
//         subcategory: 'Wholesale Distribution',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'info@prodistributors.com',
//         phone: '+1 650-901-2345',
//         address: '606 Pro St, San Francisco, CA',
//         hours: {
//             Monday: '8:00 AM - 6:00 PM',
//             Tuesday: '8:00 AM - 6:00 PM',
//             Wednesday: '8:00 AM - 6:00 PM',
//             Thursday: '8:00 AM - 6:00 PM',
//             Friday: '8:00 AM - 6:00 PM',
//             Saturday: 'Closed',
//             Sunday: 'Closed',
//         },
//         description: 'Professional wholesale distribution with a focus on reliability.',
//         services: [
//             { name: 'Reliable Distribution', description: 'Dependable wholesale distribution services.', price: '$2000' },
//             { name: 'Order Fulfillment', description: 'Efficient order fulfillment services.', price: '$1400' },
//         ],
//     },
    
//     // Distribution - Retail Distribution
//     {
//         _id: 16,
//         name: 'RetailPlus',
//         category: 'Distribution',
//         subcategory: 'Retail Distribution',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'contact@retailplus.com',
//         phone: '+1 650-123-4567',
//         address: '123 Retail Blvd, San Francisco, CA',
//         hours: {
//             Monday: '10:00 AM - 8:00 PM',
//             Tuesday: '10:00 AM - 8:00 PM',
//             Wednesday: '10:00 AM - 8:00 PM',
//             Thursday: '10:00 AM - 8:00 PM',
//             Friday: '10:00 AM - 8:00 PM',
//             Saturday: '10:00 AM - 6:00 PM',
//             Sunday: 'Closed',
//         },
//         description: 'Retail distribution solutions for stores and outlets.',
//         services: [
//             { name: 'Store Supply', description: 'Supply for retail stores and shops.', price: '$1500' },
//             { name: 'Retail Logistics', description: 'Efficient logistics for retail distribution.', price: '$1200' },
//         ],
//     },
//     {
//         _id: 17,
//         name: 'ShopStream',
//         category: 'Distribution',
//         subcategory: 'Retail Distribution',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'info@shopstream.com',
//         phone: '+1 650-234-5678',
//         address: '456 Shop St, San Francisco, CA',
//         hours: {
//             Monday: '10:00 AM - 8:00 PM',
//             Tuesday: '10:00 AM - 8:00 PM',
//             Wednesday: '10:00 AM - 8:00 PM',
//             Thursday: '10:00 AM - 8:00 PM',
//             Friday: '10:00 AM - 8:00 PM',
//             Saturday: '10:00 AM - 6:00 PM',
//             Sunday: 'Closed',
//         },
//         description: 'Streamlined retail distribution services for a seamless supply chain.',
//         services: [
//             { name: 'Retail Supply Chain', description: 'Manage and optimize retail supply chains.', price: '$1800' },
//             { name: 'Product Distribution', description: 'Efficient product distribution for retailers.', price: '$1400' },
//         ],
//     },
//     {
//         _id: 18,
//         name: 'StoreLink',
//         category: 'Distribution',
//         subcategory: 'Retail Distribution',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'contact@storelink.com',
//         phone: '+1 650-345-6789',
//         address: '789 Store Ave, San Francisco, CA',
//         hours: {
//             Monday: '10:00 AM - 8:00 PM',
//             Tuesday: '10:00 AM - 8:00 PM',
//             Wednesday: '10:00 AM - 8:00 PM',
//             Thursday: '10:00 AM - 8:00 PM',
//             Friday: '10:00 AM - 8:00 PM',
//             Saturday: '10:00 AM - 6:00 PM',
//             Sunday: 'Closed',
//         },
//         description: 'Connecting retail stores with effective distribution solutions.',
//         services: [
//             { name: 'Retail Distribution', description: 'Efficient distribution for retail businesses.', price: '$1600' },
//             { name: 'Store Inventory', description: 'Manage store inventory efficiently.', price: '$1300' },
//         ],
//     },
//     {
//         _id: 19,
//         name: 'RetailLinker',
//         category: 'Distribution',
//         subcategory: 'Retail Distribution',
//         images: ['https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=2970&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'],
//         email: 'info@retaillinker.com',
//         phone: '+1 650-456-7890',
//         address: '101 Retail Ln, San Francisco, CA',
//         hours: {
//             Monday: '10:00 AM - 8:00 PM',
//             Tuesday: '10:00 AM - 8:00 PM',
//             Wednesday: '10:00 AM - 8:00 PM',
//             Thursday: '10:00 AM - 8:00 PM',
//             Friday: '10:00 AM - 8:00 PM',
//             Saturday: '10:00 AM - 6:00 PM',
//             Sunday: 'Closed',
//         },
//         description: 'Expert solutions for retail distribution and logistics.',
//         services: [
//             { name: 'Logistics Solutions', description: 'Comprehensive logistics solutions for retail.', price: '$1700' },
//             { name: 'Retail Management', description: 'Manage retail operations and supply.', price: '$1300' },
//         ],
//     },
//     {
//         _id: 20,
//         images: ["https://mui.com/static/images/cards/contemplative-reptile.jpg"],
//         name: "Strategic Insights Consulting",
//         category: "Consultancy Services",
//         subcategory: "Business",
//         rating: 4.5,
//         description: "Offering expert business consulting services to help you streamline operations and drive growth. Specializing in strategic planning and market analysis.",
//         email: "info@strategicinsights.com",
//         phone: "+1 650-123-4567",
//         address: "101 Strategy Lane, San Francisco, CA",
//         hours: {
//             Monday: "9:00 AM - 5:00 PM",
//             Tuesday: "9:00 AM - 5:00 PM",
//             Wednesday: "9:00 AM - 5:00 PM",
//             Thursday: "9:00 AM - 5:00 PM",
//             Friday: "9:00 AM - 5:00 PM",
//             Saturday: "Closed",
//             Sunday: "Closed"
//         },
//         services: [
//             { name: "Business Strategy", description: "Develop and implement effective business strategies.", price: "$1500" },
//             { name: "Market Analysis", description: "Analyze market trends and competitor strategies.", price: "$1200" }
//         ]
//     },
//     {
//         _id: 21,
//         images: ["https://images.unsplash.com/photo-1549778399-f94fd24d4697?q=80&w=3174&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
//         name: "Tech Innovators IT Solutions",
//         category: "Consultancy Services",
//         subcategory: "IT",
//         rating: 4.7,
//         description: "Providing comprehensive IT consulting services, including system integration, cybersecurity, and cloud solutions for businesses of all sizes.",
//         email: "support@techinnovators.com",
//         phone: "+1 650-234-5678",
//         address: "202 Tech Ave, San Francisco, CA",
//         hours: {
//             Monday: "9:00 AM - 6:00 PM",
//             Tuesday: "9:00 AM - 6:00 PM",
//             Wednesday: "9:00 AM - 6:00 PM",
//             Thursday: "9:00 AM - 6:00 PM",
//             Friday: "9:00 AM - 6:00 PM",
//             Saturday: "Closed",
//             Sunday: "Closed"
//         },
//         services: [
//             { name: "System Integration", description: "Integrate different IT systems and technologies.", price: "$2000" },
//             { name: "Cybersecurity", description: "Protect your business from cyber threats.", price: "$1800" },
//             { name: "Cloud Solutions", description: "Implement and manage cloud-based services.", price: "$1700" }
//         ]
//     },
//     {
//         _id: 22,
//         images: ["https://images.unsplash.com/photo-1548614229-c1fe21dfab63?q=80&w=3165&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
//         name: "Career Pathways Recruitment",
//         category: "Consultancy Services",
//         subcategory: "Job/Recruitment",
//         rating: 3.9,
//         description: "Helping organizations find top talent and offering career coaching services to job seekers. Specializing in recruitment and career development strategies.",
//         email: "contact@careerpathways.com",
//         phone: "+1 650-345-6789",
//         address: "303 Career St, San Francisco, CA",
//         hours: {
//             Monday: "9:00 AM - 5:00 PM",
//             Tuesday: "9:00 AM - 5:00 PM",
//             Wednesday: "9:00 AM - 5:00 PM",
//             Thursday: "9:00 AM - 5:00 PM",
//             Friday: "9:00 AM - 5:00 PM",
//             Saturday: "Closed",
//             Sunday: "Closed"
//         },
//         services: [
//             { name: "Talent Acquisition", description: "Find and recruit top talent for your organization.", price: "$1500" },
//             { name: "Career Coaching", description: "Provide career guidance and coaching for job seekers.", price: "$1200" }
//         ]
//     },
//     {
//         _id: 23,
//         images: ["https://images.unsplash.com/photo-1548602088-9d12a4f9c10f?q=80&w=2952&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
//         name: "Future Leaders Education Consultants",
//         category: "Consultancy Services",
//         subcategory: "Education",
//         rating: 5,
//         description: "Expert consultants offering educational advice and planning services for students and educational institutions. Specializing in college admissions and curriculum design.",
//         email: "info@futureleaders.com",
//         phone: "+1 650-456-7890",
//         address: "404 Education Blvd, San Francisco, CA",
//         hours: {
//             Monday: "9:00 AM - 6:00 PM",
//             Tuesday: "9:00 AM - 6:00 PM",
//             Wednesday: "9:00 AM - 6:00 PM",
//             Thursday: "9:00 AM - 6:00 PM",
//             Friday: "9:00 AM - 6:00 PM",
//             Saturday: "Closed",
//             Sunday: "Closed"
//         },
//         services: [
//             { name: "College Admissions", description: "Assist with the college application process.", price: "$2000" },
//             { name: "Curriculum Design", description: "Help design and implement educational curriculums.", price: "$1800" }
//         ]
//     },
//     {
//         _id: 24,
//         images: ["https://images.unsplash.com/photo-1548506923-99f6e89852fe?q=80&w=2974&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
//         name: "Wellness Consulting Group",
//         category: "Consultancy Services",
//         subcategory: "Health",
//         rating: 4.2,
//         description: "Offering health consulting services to improve wellness programs and healthcare strategies for organizations and individuals.",
//         email: "contact@wellnessconsulting.com",
//         phone: "+1 650-567-8901",
//         address: "505 Wellness Rd, San Francisco, CA",
//         hours: {
//             Monday: "9:00 AM - 6:00 PM",
//             Tuesday: "9:00 AM - 6:00 PM",
//             Wednesday: "9:00 AM - 6:00 PM",
//             Thursday: "9:00 AM - 6:00 PM",
//             Friday: "9:00 AM - 6:00 PM",
//             Saturday: "Closed",
//             Sunday: "Closed"
//         },
//         services: [
//             { name: "Wellness Programs", description: "Design and implement wellness programs.", price: "$1500" },
//             { name: "Healthcare Strategy", description: "Develop strategies for effective healthcare management.", price: "$1300" }
//         ]
//     },
//     {
//         _id: 25,
//         images: ["https://images.unsplash.com/photo-1548413935-a7d015ff5865?q=80&w=2111&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"],
//         name: "Global Trade Wholesale",
//         category: "Distribution",
//         subcategory: "Wholesale Distribution",
//         rating: 3.6,
//         description: "Specializing in wholesale distribution of consumer goods, providing efficient logistics and supply chain solutions for businesses worldwide.",
//         email: "sales@globaltradewholesale.com",
//         phone: "+1 650-678-9012",
//         address: "606 Trade Ave, San Francisco, CA",
//         hours: {
//             Monday: "8:00 AM - 6:00 PM",
//             Tuesday: "8:00 AM - 6:00 PM",
//             Wednesday: "8:00 AM - 6:00 PM",
//             Thursday: "8:00 AM - 6:00 PM",
//             Friday: "8:00 AM - 6:00 PM",
//             Saturday: "Closed",
//             Sunday: "Closed"
//         },
//         services: [
//             { name: "Bulk Distribution", description: "Wholesale distribution for large orders.", price: "$2500" },
//             { name: "Logistics Solutions", description: "Efficient logistics and supply chain management.", price: "$2000" }
//         ]
//     }    
// ];

const businessDataList = [
    {
        "_id": "1",
        "name": "The Coffee Haven",
        "email": "info@thecoffeehaven.com",
        "phone": "+1-234-567-8901",
        "street": "123 Brew St",
        "city": "Caffeine City",
        "province": "CA",
        "postalCode": "C1F 2G3",
        "isVirtualOnly": false,
        "country": "US",
        "photoUrls": [
            "https://picsum.photos/200",
            "https://picsum.photos/200",
            "https://picsum.photos/200",
            "https://picsum.photos/200",
            "https://picsum.photos/200"
        ],
        "website": "https://thecoffeehaven.com",
        "category": {
            "_id": "1",
            "name": "Food & Drink",
            "image": "https://picsum.photos/200",
            "subcategories": [],
            "numBusiness": 1,
            "description": "Businesses that provide food and drink services."
        },
        "subCategory": {
            "_id": "1",
            "name": "Café",
            "description": "A small restaurant selling light meals and drinks.",
            "parentCategory": "Food & Drink",
            "numBusiness": 1,
        },
        "description": "A cozy café offering a variety of coffees, teas, and light snacks. Perfect for remote work or catching up with friends.",
        "hours": {
            "Monday": { "checked": true, "start": "18", "end": "34" },
            "Tuesday": { "checked": true, "start": "18", "end": "34" },
            "Wednesday": { "checked": true, "start": "18", "end": "34" },
            "Thursday": { "checked": true, "start": "18", "end": "34" },
            "Friday": { "checked": true, "start": "18", "end": "34" },
            "Saturday": { "checked": false, "start": "", "end": "" },
            "Sunday": { "checked": false, "start": "", "end": "" }
        },
        "ratings": 4.5,
        "tags": ["coffee", "café", "snacks", "cozy", "remote work"],
        "listingUser": {
            "userId": "user123",
            "username": "coffeeLover",
            "profilePicture": "https://example.com/users/coffeeLover.jpg"
        },
        "offerings": [
            {
                "type": "product",
                "name": "Specialty Coffee",
                "description": "Handcrafted coffee brewed from the finest beans.",
                "price": {
                    "value": "4.50",
                    "currency": "USD"
                }
            },
            {
                "type": "product",
                "name": "Pastry of the Day",
                "description": "Freshly baked pastry, changes daily.",
            },
            {
                "type": "product",
                "name": "Pastry of the Day",
                "description": "Freshly baked pastry, changes daily.",
            },
            {
                "type": "product",
                "name": "Pastry of the Day",
                "description": "Freshly baked pastry, changes daily.",
            }
        ],
        "socialMedia": {
            "facebook": "https://facebook.com/thecoffeehaven",
            "instagram": "https://instagram.com/thecoffeehaven",
            "twitter": "https://twitter.com/thecoffeehaven"
        },
        "authorizedUsers": []
    },
    {
        "_id": "2",
        "name": "The Green Thumb",
        "email": "",
        "phone": "+1-234-567-8902",
        "street": "456 Plant St",
        "city": "Garden Grove",
        "province": "CA",
        "postalCode": "G4H 5J6",
        "isVirtualOnly": false,
        "country": "US",
        "photoUrls": [
            "https://picsum.photos/200",
            "https://picsum.photos/200",
            "https://picsum.photos/200",
            "https://picsum.photos/200",
            "https://picsum.photos/200"
        ],
        "website": "https://thegreenthumb.com",
        "category": {
            "_id": "2",
            "name": "Home & Garden",
            "image": "https://picsum.photos/200",
            "subcategories": [],
            "numBusiness": 1,
            "description": "Businesses that provide home and garden products and services."
        },
        "subCategory": {
            "_id": "1",
            "name": "Gardening",
            "description": "Businesses that provide gardening products and services.",
            "parentCategory": "Home & Garden",
            "numBusiness": 1,
        },
        "description": "A plant lover's paradise with a wide selection of indoor and outdoor plants, gardening tools, and accessories.",
        "hours": {
            "Monday": { "checked": true, "start": "18", "end": "34" },
            "Tuesday": { "checked": true, "start": "18", "end": "34" },
            "Wednesday": { "checked": true, "start": "18", "end": "34" },
            "Thursday": { "checked": true, "start": "18", "end": "34" },
            "Friday": { "checked": true, "start": "18", "end": "34" },
            "Saturday": { "checked": false, "start": "", "end": "" },
            "Sunday": { "checked": false, "start": "", "end": "" }
        },
        "ratings": 4.7,
        "tags": ["plants", "gardening", "tools", "accessories", "green thumb"],
        "listingUser": {
            "userId": "user123",
            "username": "plantLover",
            "profilePicture": "https://example.com/users/plantLover.jpg"
        },
        "offerings": [
            {
                "type": "product",
                "name": "Succulent Collection",
                "description": "Assorted succulents in decorative pots.",
                "price": {
                    "value": "20.00",
                    "currency": "USD"
                }
            },
            {
                "type": "product",
                "name": "Gardening Tool Set",
                "description": "Basic tools for beginner gardeners.",
                "price": {
                    "value": "30.00",
                    "currency": "USD"
                }
            }
        ],
        "socialMedia": {
            "facebook": "https://facebook.com/thegreenthumb",
            "instagram": "https://instagram.com/thegreenthumb",
            "twitter": "https://twitter.com/thegreenthumb"
        },
        "authorizedUsers": []
    },  
];

export default businessDataList;