export const provinceList = [
    { _id: "AB", name: "Alberta" },
    { _id: "BC", name: "British Columbia" },
    { _id: "MB", name: "Manitoba" },
    { _id: "NB", name: "New Brunswick" },
    { _id: "NL", name: "Newfoundland and Labrador" },
    { _id: "NS", name: "Nova Scotia" },
    { _id: "NT", name: "Northwest Territories" },
    { _id: "NU", name: "Nunavut" },
    { _id: "ON", name: "Ontario" },
    { _id: "PE", name: "Prince Edward Island" },
    { _id: "QC", name: "Quebec" },
    { _id: "SK", name: "Saskatchewan" },
    { _id: "YT", name: "Yukon" }
];

export const stateList = [
    { _id: "AL", name: "Alabama" },
    { _id: "AK", name: "Alaska" },
    { _id: "AZ", name: "Arizona" },
    { _id: "AR", name: "Arkansas" },
    { _id: "CA", name: "California" },
    { _id: "CO", name: "Colorado" },
    { _id: "CT", name: "Connecticut" },
    { _id: "DE", name: "Delaware" },
    { _id: "DC", name: "District Of Columbia" },
    { _id: "FL", name: "Florida" },
    { _id: "GA", name: "Georgia" },
    { _id: "HI", name: "Hawaii" },
    { _id: "ID", name: "Idaho" },
    { _id: "IL", name: "Illinois" },
    { _id: "IN", name: "Indiana" },
    { _id: "IA", name: "Iowa" },
    { _id: "KS", name: "Kansas" },
    { _id: "KY", name: "Kentucky" },
    { _id: "LA", name: "Louisiana" },
    { _id: "ME", name: "Maine" },
    { _id: "MD", name: "Maryland" },
    { _id: "MA", name: "Massachusetts" },
    { _id: "MI", name: "Michigan" },
    { _id: "MN", name: "Minnesota" },
    { _id: "MS", name: "Mississippi" },
    { _id: "MO", name: "Missouri" },
    { _id: "MT", name: "Montana" },
    { _id: "NE", name: "Nebraska" },
    { _id: "NV", name: "Nevada" },
    { _id: "NH", name: "New Hampshire" },
    { _id: "NJ", name: "New Jersey" },
    { _id: "NM", name: "New Mexico" },
    { _id: "NY", name: "New York" },
    { _id: "NC", name: "North Carolina" },
    { _id: "ND", name: "North Dakota" },
    { _id: "OH", name: "Ohio" },
    { _id: "OK", name: "Oklahoma" },
    { _id: "OR", name: "Oregon" },
    { _id: "PA", name: "Pennsylvania" },
    { _id: "RI", name: "Rhode Island" },
    { _id: "SC", name: "South Carolina" },
    { _id: "SD", name: "South Dakota" },
    { _id: "TN", name: "Tennessee" },
    { _id: "TX", name: "Texas" },
    { _id: "UT", name: "Utah" },
    { _id: "VT", name: "Vermont" },
    { _id: "VA", name: "Virginia" },
    { _id: "WA", name: "Washington" },
    { _id: "WV", name: "West Virginia" },
    { _id: "WI", name: "Wisconsin" },
    { _id: "WY", name: "Wyoming" },
    { _id: "AS", name: "American Samoa" },
    { _id: "GU", name: "Guam" },
    { _id: "MP", name: "Northern Mariana Islands" },
    { _id: "PR", name: "Puerto Rico" },
    { _id: "UM", name: "United States Minor Outlying Islands" },
    { _id: "VI", name: "Virgin Islands" }
];

export const countryList = [
    { _id: "CA", name: "Canada", provinces: provinceList },
    { _id: "US", name: "United States", provinces: stateList }
]

export const currencyList = [
    { _id: "CAD", name: "CAD", symbol: "C$" },
    { _id: "USD", name: "USD", symbol: "$" }
];

export const businessTagOptions = [
    "3D Printing",
    "Agile Methodologies",
    "Artificial Intelligence",
    "Augmented Reality",
    "Big Data",
    "Blockchain",
    "Business Development",
    "Business Intelligence",
    "Career Development",
    "Certifications",
    "Change Management",
    "Cloud Computing",
    "Collaboration",
    "Consulting",
    "Content Creation",
    "Co-Working Spaces",
    "Corporate Strategy",
    "Customer Experience",
    "Customer Service",
    "Cybersecurity",
    "Data Analysis",
    "Design Thinking",
    "Digital Marketing",
    "Digital Transformation",
    "Diversity & Inclusion",
    "E-Commerce",
    "Education",
    "Employee Engagement",
    "Entrepreneurship",
    "Ethical Hacking",
    "Finance",
    "Freelancing",
    "Global Networking",
    "Graphic Design",
    "Green Technology",
    "Healthcare",
    "Human Resources",
    "Industry Hubs",
    "Industry Trends",
    "Innovation",
    "Innovation Management",
    "Internet of Things",
    "Investment Strategies",
    "Knowledge Management",
    "Leadership",
    "Lean Startup",
    "Legal",
    "Local Business",
    "Logistics",
    "Machine Learning",
    "Manufacturing",
    "Marketing",
    "Mentorship",
    "Mobile Development",
    "Mobile Marketing",
    "Networking Events",
    "Non-Profit",
    "Open Source",
    "Organizational Development",
    "Performance Management",
    "Process Improvement",
    "Product Management",
    "Productivity",
    "Project Management",
    "Public Speaking",
    "Quality Assurance",
    "Quantum Computing",
    "Real Estate",
    "Remote Work",
    "Research & Development",
    "Retail",
    "Risk Management",
    "SaaS",
    "Sales",
    "Service Design",
    "Skill Building",
    "Smart Cities",
    "Social Media Management",
    "Software Development",
    "Startup",
    "Strategic Planning",
    "Supply Chain Management",
    "Sustainability",
    "Talent Acquisition",
    "Team Building",
    "Tech Trends",
    "Technology",
    "Telecommunications",
    "User Experience",
    "User Interface Design",
    "User Research",
    "Venture Capital",
    "Video Production",
    "Virtual Reality",
    "Virtual Teams",
    "Voice Technology",
    "Wearable Technology",
    "Webinars",
    "Wellness Programs",
    "Work-Life Balance",
    "Workforce Development",
    "Workshops",
];
  

  